version: 2

models:
  - name: jamestest
    description: changess1
    columns:
      - name: id
        description: The primary key for this table


  - name: jamestest2
    description: A starter dbt model
    columns:
      - name: id
        description: The primary key for this table

